### ISSUE TITLE
Hook incorrectly named?

### ISSUE THREAD

**Issue by emrickgarrett** [WaywardGame/mod-reference#1]
Was messing around with your library and noticed this... not sure if intentional or not. The hook name mentioned and the actual hook method name don't seem to be the same. I believe they refer to the same method, but wasn't sure.

Hook:

`OnAddOrUpdateInventoryItem = 12,`

Method: 

```
         /**
         * Called when an item is called to the players inventory
         * @param item The item object
         * @param container The container object the item was added to
         */
        onAddItemToInventory(item: Item.IItem, container: Item.IContainer): void;
```

**Comment by Spacetech** [comment]
Good catch! It will be fixed in the next release.
